[package]
name = "fulton"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
futures-util = "0.3.25"
tokio = { version = "1.23.0", features = ["full"] }
warp = "0.3.3"